// templates/clean-api/_variants/frontend/angular/src/app/features/reports/pages/reports.page.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { firstValueFrom } from 'rxjs';
import { AsyncStateComponent } from '../../../shared/components/async-state.component';
import { PageHeaderComponent } from '../../../shared/components/page-header.component';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { OrderStatusReportComponent } from '../components/order-status-report.component';
import { TopProductsReportComponent } from '../components/top-products-report.component';
import { ReportsApiService } from '../data-access/reports-api.service';
import type { OrderStatusReport, TopProductReport } from '../report.models';

@Component({ selector:'app-reports-page', standalone:true, imports:[MatButtonModule,PageHeaderComponent,AsyncStateComponent,TopProductsReportComponent,OrderStatusReportComponent], styles:[`:host{display:block}.reports{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:16px}@media(max-width:959px){.reports{grid-template-columns:1fr}}`], template:`<app-page-header eyebrow="Analytics" title="Reports" description="Focused business signals without turning the starter into an ERP."><div pageActions><button mat-stroked-button (click)="load()" [disabled]="loading()">Refresh</button></div></app-page-header><app-async-state [loading]="loading()" [error]="error()" [showRetry]="true" (retry)="load()"/>@if(!loading()&&!error()){<section class="reports"><app-top-products-report [rows]="topProducts()"/><app-order-status-report [rows]="statuses()"/></section>}` })
export class ReportsPage implements OnInit { readonly loading=signal(false); readonly error=signal<string|null>(null); readonly topProducts=signal<TopProductReport[]>([]); readonly statuses=signal<OrderStatusReport[]>([]); private readonly api=inject(ReportsApiService); ngOnInit(){void this.load();} async load(){this.loading.set(true);this.error.set(null);try{const [products,statuses]=await Promise.all([firstValueFrom(this.api.topProducts()),firstValueFrom(this.api.ordersByStatus())]);this.topProducts.set(products);this.statuses.set(statuses);}catch(error){this.error.set(getErrorMessage(error));}finally{this.loading.set(false);}} }

// templates/clean-api/_variants/frontend/react/src/features/reports/pages/ReportsPage.tsx
import RefreshOutlinedIcon from '@mui/icons-material/RefreshOutlined';
import { Box, Button } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { AsyncState } from '../../../shared/components/AsyncState';
import { PageHeader } from '../../../shared/components/PageHeader';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { reportsApi } from '../api/reports.api';
import { OrderStatusReportCard } from '../components/OrderStatusReportCard';
import { TopProductsReportCard } from '../components/TopProductsReportCard';

export function ReportsPage() {
  const topProducts = useQuery({ queryKey: ['reports', 'top-products'], queryFn: reportsApi.topProducts });
  const statuses = useQuery({ queryKey: ['reports', 'orders-by-status'], queryFn: reportsApi.ordersByStatus });
  const loading = topProducts.isLoading || statuses.isLoading;
  const error = topProducts.isError ? getErrorMessage(topProducts.error) : statuses.isError ? getErrorMessage(statuses.error) : null;
  const refresh = () => { void topProducts.refetch(); void statuses.refetch(); };

  return <Box component="section"><PageHeader eyebrow="Analytics" title="Reports" description="Focused business signals without turning the starter into an ERP." actions={<Button variant="outlined" startIcon={<RefreshOutlinedIcon />} onClick={refresh} disabled={topProducts.isFetching || statuses.isFetching}>Refresh</Button>} /><AsyncState loading={loading} error={error} onRetry={refresh} />{!loading && !error && <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'minmax(0,1.25fr) minmax(320px,.75fr)' }, gap: 2 }}><TopProductsReportCard rows={topProducts.data ?? []} /><OrderStatusReportCard rows={statuses.data ?? []} /></Box>}</Box>;
}
