// templates/clean-api/_variants/frontend/angular/src/app/app.component.ts
import { Component,OnInit,inject,signal } from '@angular/core';
import { AuthSessionService,AuthUser } from './core/auth/auth-session.service';
import { LoginPage } from './features/auth/login.page';
import { ProfilePage } from './features/profile/profile.page';
import { TodoPage } from './features/todos/todo.page';
import { UsersPage } from './features/users/users.page';
import { AppShellComponent } from './shared/components/app-shell.component';
@Component({selector:'app-root',standalone:true,imports:[LoginPage,ProfilePage,TodoPage,UsersPage,AppShellComponent],template:`@if(!ready()){<main class="shell"><p>Restoring session…</p></main>}@else if(!auth.user()){<app-login-page (authenticated)="onAuthenticated($event)"/>}@else{<app-shell [user]="auth.user()!" (logout)="onLogout()"><app-profile-page/>@if(auth.can('users.read')){<app-users-page/>}@if(auth.can('todos.read')){<app-todo-page/>}</app-shell>}`})
export class AppComponent implements OnInit{readonly auth=inject(AuthSessionService);readonly ready=signal(false);async ngOnInit(){await this.auth.bootstrap();this.ready.set(true);}onAuthenticated(_user:AuthUser){}async onLogout(){await this.auth.logout();}}

// templates/clean-api/_variants/frontend-app/react-storage/src/app/App.tsx
import { useEffect, useState } from 'react';
import { bootstrapAuth, can, logout, type AuthUser } from '../core/auth/auth-session';
import { LoginPage } from '../features/auth/LoginPage';
import { ProfilePage } from '../features/profile/ProfilePage';
import { TodoPage } from '../features/todos/TodoPage';
import { UsersPage } from '../features/users/UsersPage';
import { AppShell } from '../shared/components/AppShell';

export function App() {
  const [user, setUser] = useState<AuthUser | null | undefined>(undefined);
  useEffect(() => { void bootstrapAuth().then(setUser); }, []);
  if (user === undefined) return <main className="shell"><p>Restoring session…</p></main>;
  if (user === null) return <LoginPage onAuthenticated={setUser} />;
  return <AppShell user={user} onLogout={() => void logout().finally(() => setUser(null))}>
    <ProfilePage user={user} onProfileUpdated={displayName => setUser(current => current ? { ...current, displayName } : current)} />
    {can(user, 'users.read') && <UsersPage canManage={can(user, 'users.manage')} />}
    {can(user, 'todos.read') && <TodoPage canWrite={can(user, 'todos.write')} />}
  </AppShell>;
}
