// templates/clean-api/_variants/frontend-features/react-storage/src/features/products/pages/ProductsPage.tsx
import AddOutlinedIcon from '@mui/icons-material/AddOutlined';
import RefreshOutlinedIcon from '@mui/icons-material/RefreshOutlined';
import { Box, Button, MenuItem, Pagination, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import type { AuthUser } from '../../../core/auth/auth-session';
import { can } from '../../../core/auth/auth-session';
import { type BusinessListQuery, type ListFilter } from '../../../shared/query/business-query';
import { AsyncState } from '../../../shared/components/AsyncState';
import { ConfirmDialog } from '../../../shared/components/ConfirmDialog';
import { PageHeader } from '../../../shared/components/PageHeader';
import { useNotifications } from '../../../shared/feedback/NotificationProvider';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { productsApi } from '../api/products.api';
import { ProductFilters } from '../components/ProductFilters';
import { ProductFormDialog } from '../components/ProductFormDialog';
import { ProductsGrid } from '../components/ProductsGrid';
import type { Product, ProductFilterState, ProductModel } from '../product.models';

type Props = { user: AuthUser };
type SaveProduct = { product: Product | null; model: ProductModel; image: File | null };

const initialFilters: ProductFilterState = { keyword: '', sort: '', active: '', lowStock: '' };
const initialQuery: BusinessListQuery = { page: 1, pageSize: 20 };
const pageSizes = [10, 20, 50, 100];

export function ProductsPage({ user }: Props) {
  const queryClient = useQueryClient();
  const notifications = useNotifications();
  const [query, setQuery] = useState<BusinessListQuery>(initialQuery);
  const [filters, setFilters] = useState<ProductFilterState>(initialFilters);
  const [editing, setEditing] = useState<Product | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<Product | null>(null);

  const products = useQuery({
    queryKey: ['products', query],
    queryFn: () => productsApi.list(query),
  });

  const save = useMutation({
    mutationFn: ({ product, model, image }: SaveProduct) => product
      ? productsApi.update(product.id, model, image)
      : productsApi.create(model, image),
    onSuccess: async (_, variables) => {
      notifications.success(variables.product ? 'Product updated.' : 'Product created.');
      setFormOpen(false);
      setEditing(null);
      await queryClient.invalidateQueries({ queryKey: ['products'] });
    },
    onError: error => notifications.error(getErrorMessage(error)),
  });

  const remove = useMutation({
    mutationFn: (product: Product) => productsApi.remove(product.id),
    onSuccess: async () => {
      notifications.success('Product deleted.');
      setDeleteTarget(null);
      await queryClient.invalidateQueries({ queryKey: ['products'] });
    },
    onError: error => notifications.error(getErrorMessage(error)),
  });

  const applyFilters = () => {
    const nextFilters: ListFilter[] = [];
    if (filters.active) nextFilters.push({ field: 'IsActive', operator: '$eq', value: filters.active === 'true' });
    if (filters.lowStock.trim()) nextFilters.push({ field: 'StockQuantity', operator: '$lte', value: Math.max(0, Number(filters.lowStock)) });
    setQuery(current => ({
      ...current,
      page: 1,
      keyword: filters.keyword.trim() || undefined,
      targets: ['Name', 'Sku'],
      sort: filters.sort || undefined,
      filters: nextFilters,
    }));
  };

  const clearFilters = () => {
    setFilters(initialFilters);
    setQuery(current => ({ page: 1, pageSize: current.pageSize }));
  };

  const page = products.data;
  const currentPage = page?.paging?.currentPage ?? query.page;
  const totalPages = page?.paging?.totalPage ?? 0;

  return (
    <Box component="section">
      <PageHeader
        eyebrow="Sales"
        title="Products"
        description="Catalog, pricing and stock at a glance."
        actions={(
          <>
            <Button variant="outlined" startIcon={<RefreshOutlinedIcon />} onClick={() => void products.refetch()} disabled={products.isFetching}>Refresh</Button>
            {can(user, 'products.create') && <Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={() => { setEditing(null); setFormOpen(true); }}>Add product</Button>}
          </>
        )}
      />

      <ProductFilters value={filters} onChange={setFilters} onApply={applyFilters} onClear={clearFilters} />

      <AsyncState
        loading={products.isLoading}
        error={products.isError ? getErrorMessage(products.error) : null}
        empty={!products.isLoading && !products.isError && (page?.data.length ?? 0) === 0}
        emptyTitle="No products yet"
        emptyMessage="Create your first product or adjust the current filters."
        onRetry={() => void products.refetch()}
      />

      {page && page.data.length > 0 && (
        <>
          <ProductsGrid
            products={page.data}
            loading={products.isFetching}
            canUpdate={can(user, 'products.update')}
            canDelete={can(user, 'products.delete')}
            onEdit={product => { setEditing(product); setFormOpen(true); }}
            onDelete={setDeleteTarget}
          />
          {page.paging && (
            <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, alignItems: { sm: 'center' }, justifyContent: 'space-between', gap: 2, mt: 2 }}>
              <Typography variant="body2" color="text.secondary">{totalPages ? `Page ${currentPage} of ${totalPages}` : 'No results'}</Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                <TextField select size="small" label="Rows" value={query.pageSize} onChange={event => setQuery(current => ({ ...current, page: 1, pageSize: Number(event.target.value) }))} sx={{ width: 100 }}>
                  {pageSizes.map(size => <MenuItem key={size} value={size}>{size}</MenuItem>)}
                </TextField>
                <Pagination count={Math.max(1, totalPages)} page={Math.max(1, currentPage)} onChange={(_, nextPage) => setQuery(current => ({ ...current, page: nextPage }))} disabled={totalPages <= 1} />
              </Box>
            </Box>
          )}
        </>
      )}

      <ProductFormDialog
        open={formOpen}
        product={editing}
        busy={save.isPending}
        onClose={() => { setFormOpen(false); setEditing(null); }}
        onSubmit={(model, image) => save.mutate({ product: editing, model, image })}
      />
      <ConfirmDialog
        open={Boolean(deleteTarget)}
        title="Delete product?"
        description={deleteTarget ? `Delete ${deleteTarget.name}? This action cannot be undone.` : ''}
        confirmLabel="Delete"
        destructive
        busy={remove.isPending}
        onClose={() => setDeleteTarget(null)}
        onConfirm={() => { if (deleteTarget) remove.mutate(deleteTarget); }}
      />
    </Box>
  );
}

// templates/clean-api/_variants/frontend-features/angular-storage/src/app/features/products/pages/products.page.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { firstValueFrom } from 'rxjs';
import { AuthSessionService } from '../../../core/auth/auth-session.service';
import type { PaginationResponse } from '../../../core/api/api.models';
import { AsyncStateComponent } from '../../../shared/components/async-state.component';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';
import { PageHeaderComponent } from '../../../shared/components/page-header.component';
import { NotificationService } from '../../../shared/feedback/notification.service';
import { FILTER_ENABLED, type BusinessListQuery, type ListFilter } from '../../../shared/query/business-query';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { ProductFiltersComponent } from '../components/product-filters.component';
import { ProductFormDialogComponent, type ProductDialogResult } from '../components/product-form-dialog.component';
import { ProductTableComponent } from '../components/product-table.component';
import { ProductsApiService } from '../data-access/products-api.service';
import type { Product, ProductFilterState, ProductModel } from '../product.models';

@Component({
  selector: 'app-products-page',
  standalone: true,
  imports: [MatButtonModule, MatFormFieldModule, MatSelectModule, PageHeaderComponent, AsyncStateComponent, ProductFiltersComponent, ProductTableComponent],
  styles: [`
    :host{display:block}.pager{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:16px;padding:12px 16px;border:1px solid var(--mat-sys-outline-variant);border-radius:16px;background:var(--mat-sys-surface)}.pager-actions{display:flex;align-items:center;gap:8px}.page-size{width:100px;margin-bottom:-20px}@media(max-width:599px){.pager{align-items:stretch;flex-direction:column}.pager-actions{justify-content:space-between}}
  `],
  template: `
    <app-page-header eyebrow="Sales" title="Products" description="Catalog, pricing and stock at a glance.">
      <div pageActions><button mat-stroked-button (click)="load()" [disabled]="loading()">Refresh</button>@if(auth.can('products.create')){<button mat-flat-button (click)="openForm(null)">Add product</button>}</div>
    </app-page-header>

    @if(filterEnabled){<app-product-filters (applyFilters)="applyFilters($event)" (clearFilters)="clearFilters()"/>}

    <app-async-state [loading]="loading()" [error]="error()" [empty]="!loading()&&!error()&&(page()?.data?.length??0)===0" [showRetry]="true" emptyTitle="No products yet" emptyMessage="Create your first product or adjust the current filters." (retry)="load()"/>

    @if(page(); as result){
      @if(result.data.length){
        <app-product-table [products]="result.data" [canUpdate]="auth.can('products.update')" [canDelete]="auth.can('products.delete')" (edit)="openForm($event)" (remove)="deleteProduct($event)"/>
        @if(result.paging){<section class="pager"><span>{{result.paging.totalPage ? 'Page '+(result.paging.currentPage ?? query.page)+' of '+result.paging.totalPage : 'No results'}}</span><div class="pager-actions"><mat-form-field class="page-size" appearance="outline"><mat-label>Rows</mat-label><mat-select [value]="query.pageSize" (selectionChange)="changePageSize($event.value)">@for(size of pageSizes;track size){<mat-option [value]="size">{{size}}</mat-option>}</mat-select></mat-form-field><button mat-button [disabled]="!result.paging.hasPreviousPage" (click)="changePage(Math.max(1,(result.paging.currentPage ?? query.page)-1))">Prev</button><button mat-button [disabled]="!result.paging.hasNextPage" (click)="changePage((result.paging.currentPage ?? query.page)+1)">Next</button></div></section>}
      }
    }
  `,
})
export class ProductsPage implements OnInit {
  readonly auth = inject(AuthSessionService);
  readonly filterEnabled = FILTER_ENABLED;
  readonly pageSizes = [10, 20, 50, 100];
  readonly Math = Math;
  readonly loading = signal(false);
  readonly error = signal<string | null>(null);
  readonly page = signal<PaginationResponse<Product> | null>(null);
  query: BusinessListQuery = { page: 1, pageSize: 20 };

  private readonly api = inject(ProductsApiService);
  private readonly dialog = inject(MatDialog);
  private readonly confirm = inject(ConfirmDialogService);
  private readonly notifications = inject(NotificationService);

  ngOnInit() { void this.load(); }

  async load() {
    this.loading.set(true); this.error.set(null);
    try { this.page.set(await firstValueFrom(this.api.list(this.query))); }
    catch (error) { this.error.set(getErrorMessage(error)); }
    finally { this.loading.set(false); }
  }

  applyFilters(filters: ProductFilterState) {
    const lhs: ListFilter[] = [];
    if (filters.active) lhs.push({ field: 'IsActive', operator: '$eq', value: filters.active === 'true' });
    if (filters.lowStock.trim()) lhs.push({ field: 'StockQuantity', operator: '$lte', value: Math.max(0, Number(filters.lowStock)) });
    this.query = { ...this.query, page: 1, keyword: filters.keyword.trim() || undefined, targets: ['Name', 'Sku'], sort: filters.sort || undefined, filters: lhs };
    void this.load();
  }

  clearFilters() { this.query = { page: 1, pageSize: this.query.pageSize }; void this.load(); }
  changePage(page: number) { this.query = { ...this.query, page }; void this.load(); }
  changePageSize(pageSize: number) { this.query = { ...this.query, page: 1, pageSize }; void this.load(); }

  async openForm(product: Product | null) {
    const result = await firstValueFrom(this.dialog.open<ProductFormDialogComponent, { product: Product | null }, ProductDialogResult>(ProductFormDialogComponent, { data: { product }, width: '620px', maxWidth: 'calc(100vw - 32px)', autoFocus: false }).afterClosed());
    if (!result) return;
    await this.saveProduct(product, result.model, result.image);
  }

  async saveProduct(product: Product | null, model: ProductModel, image: File | null) {
    try {
      if (product) await firstValueFrom(this.api.update(product.id, model, image));
      else await firstValueFrom(this.api.create(model, image));
      this.notifications.success(product ? 'Product updated.' : 'Product created.');
      await this.load();
    } catch (error) { this.notifications.error(getErrorMessage(error)); }
  }

  async deleteProduct(product: Product) {
    const confirmed = await this.confirm.confirm({ title: 'Delete product?', description: `Delete ${product.name}? This action cannot be undone.`, confirmLabel: 'Delete', destructive: true });
    if (!confirmed) return;
    try { await firstValueFrom(this.api.remove(product.id)); this.notifications.success('Product deleted.'); await this.load(); }
    catch (error) { this.notifications.error(getErrorMessage(error)); }
  }
}
