// templates/clean-api/_variants/frontend/react/src/features/employees/components/EmployeeFormDialog.tsx
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField } from '@mui/material';
import { useEffect, useState } from 'react';
import { EMPLOYEE_ROLES, type CreateEmployeeModel, type EmployeeRole } from '../employee.models';

type Props = {
  open: boolean;
  busy: boolean;
  onClose: () => void;
  onSubmit: (model: CreateEmployeeModel) => void;
};

const emptyEmployee = (): CreateEmployeeModel => ({
  email: '',
  password: '',
  displayName: '',
  role: 'Staff',
});

export function EmployeeFormDialog({ open, busy, onClose, onSubmit }: Props) {
  const [model, setModel] = useState<CreateEmployeeModel>(emptyEmployee);

  useEffect(() => {
    if (open) setModel(emptyEmployee());
  }, [open]);

  const valid = Boolean(model.displayName.trim() && model.email.trim() && model.password);

  return (
    <Dialog open={open} onClose={busy ? undefined : onClose} maxWidth="sm" fullWidth>
      <DialogTitle>Add employee</DialogTitle>
      <DialogContent sx={{ display: 'grid', gap: 2, pt: '12px !important' }}>
        <TextField autoFocus label="Display name" value={model.displayName} onChange={event => setModel(current => ({ ...current, displayName: event.target.value }))} required />
        <TextField label="Email" type="email" value={model.email} onChange={event => setModel(current => ({ ...current, email: event.target.value }))} required />
        <TextField label="Temporary password" type="password" autoComplete="new-password" value={model.password} onChange={event => setModel(current => ({ ...current, password: event.target.value }))} required />
        <TextField select label="Role" value={model.role} onChange={event => setModel(current => ({ ...current, role: event.target.value as EmployeeRole }))}>
          {EMPLOYEE_ROLES.map(role => <MenuItem key={role} value={role}>{role}</MenuItem>)}
        </TextField>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={busy}>Cancel</Button>
        <Button variant="contained" disabled={busy || !valid} onClick={() => onSubmit({ ...model, displayName: model.displayName.trim(), email: model.email.trim() })}>
          {busy ? 'Creating…' : 'Create employee'}
        </Button>
      </DialogActions>
    </Dialog>
  );
}

// templates/clean-api/_variants/frontend/angular/src/app/features/employees/components/employee-form-dialog.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { EMPLOYEE_ROLES, type CreateEmployeeModel, type EmployeeRole } from '../employee.models';

@Component({
  selector: 'app-employee-form-dialog',
  standalone: true,
  imports: [ReactiveFormsModule, MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h2 mat-dialog-title>Add employee</h2>
    <mat-dialog-content>
      <form [formGroup]="form" class="form">
        <mat-form-field appearance="outline"><mat-label>Display name</mat-label><input matInput formControlName="displayName"/><mat-error>Display name is required.</mat-error></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"/><mat-error>Enter a valid email address.</mat-error></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Temporary password</mat-label><input matInput type="password" autocomplete="new-password" formControlName="password"/><mat-error>Password is required.</mat-error></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Role</mat-label><mat-select formControlName="role">@for(role of roles;track role){<mat-option [value]="role">{{role}}</mat-option>}</mat-select></mat-form-field>
      </form>
    </mat-dialog-content>
    <mat-dialog-actions align="end"><button mat-button (click)="dialogRef.close()">Cancel</button><button mat-flat-button [disabled]="form.invalid" (click)="submit()">Create employee</button></mat-dialog-actions>
  `,
  styles: [`.form{display:grid;gap:8px;min-width:0;padding-top:8px}`],
})
export class EmployeeFormDialogComponent {
  readonly dialogRef = inject(MatDialogRef<EmployeeFormDialogComponent, CreateEmployeeModel | undefined>);
  readonly roles = EMPLOYEE_ROLES;
  readonly form = new FormGroup({
    displayName: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    email: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.email] }),
    password: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    role: new FormControl<EmployeeRole>('Staff', { nonNullable: true }),
  });

  submit() {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    const value = this.form.getRawValue();
    this.dialogRef.close({ ...value, displayName: value.displayName.trim(), email: value.email.trim() });
  }
}
