// templates/clean-api/_variants/frontend/angular/src/app/features/products/components/product-filters.component.ts
import { ChangeDetectionStrategy, Component, output } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import type { ProductFilterState } from '../product.models';

@Component({
  selector: 'app-product-filters',
  standalone: true,
  imports: [ReactiveFormsModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`
    :host{display:block;margin-bottom:16px}.filters{padding:16px;border:1px solid var(--mat-sys-outline-variant);border-radius:16px;background:var(--mat-sys-surface)}.grid{display:grid;grid-template-columns:minmax(240px,2fr) repeat(3,minmax(150px,1fr));gap:12px}.actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.hint{color:var(--mat-sys-on-surface-variant);font-size:12px}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:599px){.grid{grid-template-columns:1fr}}
  `],
  template: `
    <form class="filters" [formGroup]="form" (ngSubmit)="submit()">
      <div class="grid">
        <mat-form-field appearance="outline"><mat-label>Search</mat-label><input matInput formControlName="keyword" placeholder="Name or SKU"/></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Sort</mat-label><mat-select formControlName="sort"><mat-option value="">Default</mat-option><mat-option value="UpdatedAt:desc">Recently updated</mat-option><mat-option value="Name:asc">Name A–Z</mat-option><mat-option value="Price:asc">Price low to high</mat-option><mat-option value="Price:desc">Price high to low</mat-option><mat-option value="StockQuantity:asc">Lowest stock</mat-option></mat-select></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Status</mat-label><mat-select formControlName="active"><mat-option value="">All</mat-option><mat-option value="true">Active</mat-option><mat-option value="false">Inactive</mat-option></mat-select></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Stock ≤</mat-label><input matInput type="number" min="0" formControlName="lowStock"/></mat-form-field>
      </div>
      <div class="actions"><button mat-flat-button type="submit">Apply</button><button mat-button type="button" (click)="clear()">Clear</button><span class="hint">LHS filters are applied before pagination.</span></div>
    </form>
  `,
})
export class ProductFiltersComponent {
  readonly applyFilters = output<ProductFilterState>();
  readonly clearFilters = output<void>();
  readonly form = new FormGroup({
    keyword: new FormControl('', { nonNullable: true }),
    sort: new FormControl('', { nonNullable: true }),
    active: new FormControl('', { nonNullable: true }),
    lowStock: new FormControl('', { nonNullable: true }),
  });

  submit() { this.applyFilters.emit(this.form.getRawValue()); }
  clear() { this.form.reset({ keyword: '', sort: '', active: '', lowStock: '' }); this.clearFilters.emit(); }
}

// templates/clean-api/_variants/frontend/react/src/features/products/components/ProductFilters.tsx
import { Box, Button, MenuItem, Paper, TextField, Typography } from '@mui/material';
import type { FormEvent } from 'react';
import { FILTER_ENABLED } from '../../../core/api/list-query';
import type { ProductFilterState } from '../product.models';

type Props = {
  value: ProductFilterState;
  onChange: (value: ProductFilterState) => void;
  onApply: () => void;
  onClear: () => void;
};

const sorts = [
  ['UpdatedAt:desc', 'Recently updated'],
  ['Name:asc', 'Name A–Z'],
  ['Price:asc', 'Price low to high'],
  ['Price:desc', 'Price high to low'],
  ['StockQuantity:asc', 'Lowest stock'],
] as const;

export function ProductFilters({ value, onChange, onApply, onClear }: Props) {
  if (!FILTER_ENABLED) return null;

  const submit = (event: FormEvent) => {
    event.preventDefault();
    onApply();
  };

  return (
    <Paper component="form" variant="outlined" onSubmit={submit} sx={{ p: 2, mb: 2 }}>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(260px,2fr) repeat(3,minmax(150px,1fr))' }, gap: 2 }}>
        <TextField
          label="Search"
          value={value.keyword}
          onChange={event => onChange({ ...value, keyword: event.target.value })}
          placeholder="Name or SKU"
          size="small"
        />
        <TextField
          select
          label="Sort"
          value={value.sort}
          onChange={event => onChange({ ...value, sort: event.target.value })}
          size="small"
        >
          <MenuItem value="">Default</MenuItem>
          {sorts.map(([sort, label]) => <MenuItem key={sort} value={sort}>{label}</MenuItem>)}
        </TextField>
        <TextField
          select
          label="Status"
          value={value.active}
          onChange={event => onChange({ ...value, active: event.target.value })}
          size="small"
        >
          <MenuItem value="">All</MenuItem>
          <MenuItem value="true">Active</MenuItem>
          <MenuItem value="false">Inactive</MenuItem>
        </TextField>
        <TextField
          label="Stock ≤"
          type="number"
          value={value.lowStock}
          onChange={event => onChange({ ...value, lowStock: event.target.value })}
          size="small"
        />
      </Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap', mt: 2 }}>
        <Button type="submit" variant="contained">Apply</Button>
        <Button type="button" variant="text" onClick={onClear}>Clear</Button>
        <Typography variant="caption" color="text.secondary">LHS filters are applied before pagination.</Typography>
      </Box>
    </Paper>
  );
}
