// templates/clean-api/_variants/frontend/react/src/features/orders/components/OrderFormDialog.tsx
import AddOutlinedIcon from '@mui/icons-material/AddOutlined';
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { formatCurrency } from '../../../shared/utils/formatters';
import type { CreateOrderModel, OrderItemModel, ProductOption } from '../order.models';

type Props = {
  open: boolean;
  products: ProductOption[];
  productsLoading: boolean;
  productsError?: string | null;
  busy: boolean;
  onClose: () => void;
  onSubmit: (model: CreateOrderModel) => void;
};

const emptyItem = (): OrderItemModel => ({ productId: '', quantity: 1 });
const emptyModel = (): CreateOrderModel => ({ customerName: '', customerPhone: null, items: [emptyItem()] });

export function OrderFormDialog({ open, products, productsLoading, productsError, busy, onClose, onSubmit }: Props) {
  const [model, setModel] = useState<CreateOrderModel>(emptyModel);

  useEffect(() => {
    if (open) setModel(emptyModel());
  }, [open]);

  const setItem = (index: number, patch: Partial<OrderItemModel>) => {
    setModel(current => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  };
  const addItem = () => setModel(current => ({ ...current, items: [...current.items, emptyItem()] }));
  const removeItem = (index: number) => setModel(current => current.items.length === 1 ? current : ({ ...current, items: current.items.filter((_, itemIndex) => itemIndex !== index) }));
  const hasItem = model.items.some(item => item.productId && item.quantity > 0);
  const submit = () => onSubmit({
    customerName: model.customerName.trim(),
    customerPhone: model.customerPhone?.trim() || null,
    items: model.items.filter(item => item.productId).map(item => ({ productId: item.productId, quantity: Math.max(1, Number(item.quantity)) })),
  });

  return (
    <Dialog open={open} onClose={busy ? undefined : onClose} maxWidth="md" fullWidth>
      <DialogTitle>New order</DialogTitle>
      <DialogContent dividers>
        <Stack spacing={2}>
          {productsError && <Alert severity="error">{productsError}</Alert>}
          <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, gap: 2 }}>
            <TextField label="Customer name" value={model.customerName} onChange={event => setModel(current => ({ ...current, customerName: event.target.value }))} autoFocus />
            <TextField label="Phone" value={model.customerPhone ?? ''} onChange={event => setModel(current => ({ ...current, customerPhone: event.target.value }))} />
          </Box>
          <Box>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 2, mb: 1 }}>
              <Typography variant="subtitle1" sx={{ fontWeight: 700 }}>Items</Typography>
              <Button startIcon={<AddOutlinedIcon />} onClick={addItem}>Add item</Button>
            </Box>
            <Stack spacing={1.5}>
              {model.items.map((item, index) => (
                <Box key={index} sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'minmax(0,1fr) 120px auto' }, gap: 1, alignItems: 'center' }}>
                  <TextField select label="Product" value={item.productId} onChange={event => setItem(index, { productId: event.target.value })} disabled={productsLoading || Boolean(productsError)}>
                    <MenuItem value="">Select product</MenuItem>
                    {products.map(product => <MenuItem key={product.id} value={product.id}>{product.name} · {formatCurrency(product.price)} · {product.stockQuantity} in stock</MenuItem>)}
                  </TextField>
                  <TextField label="Quantity" type="number" value={item.quantity} onChange={event => setItem(index, { quantity: Math.max(1, Number(event.target.value)) })} slotProps={{ htmlInput: { min: 1 } }} />
                  <Button type="button" size="small" color="error" onClick={() => removeItem(index)} disabled={model.items.length === 1}>Remove</Button>
                </Box>
              ))}
            </Stack>
            {productsLoading && <Typography variant="caption" color="text.secondary">Loading active products…</Typography>}
          </Box>
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={busy}>Cancel</Button>
        <Button variant="contained" onClick={submit} disabled={busy || productsLoading || Boolean(productsError) || !model.customerName.trim() || !hasItem}>{busy ? 'Creating…' : 'Create order'}</Button>
      </DialogActions>
    </Dialog>
  );
}

// templates/clean-api/_variants/frontend/angular/src/app/features/orders/components/order-form-dialog.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { formatCurrency } from '../../../shared/utils/formatters';
import type { CreateOrderModel, ProductOption } from '../order.models';

export type OrderFormDialogData = { products: ProductOption[] };

@Component({
  selector: 'app-order-form-dialog',
  standalone: true,
  imports: [ReactiveFormsModule, MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`
    .customer-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.items-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:8px 0}.items{display:grid;gap:12px}.item{display:grid;grid-template-columns:minmax(0,1fr) 120px auto;gap:8px;align-items:center}.full{width:100%}@media(max-width:599px){.customer-grid,.item{grid-template-columns:1fr}}
  `],
  template: `
    <h2 mat-dialog-title>New order</h2>
    <mat-dialog-content [formGroup]="form">
      <div class="customer-grid">
        <mat-form-field appearance="outline"><mat-label>Customer name</mat-label><input matInput formControlName="customerName"/></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Phone</mat-label><input matInput formControlName="customerPhone"/></mat-form-field>
      </div>
      <div class="items-heading"><strong>Items</strong><button mat-button type="button" (click)="addItem()">Add item</button></div>
      <div class="items" formArrayName="items">
        @for(item of items.controls;track $index;let i=$index){
          <div class="item" [formGroupName]="i">
            <mat-form-field class="full" appearance="outline"><mat-label>Product</mat-label><mat-select formControlName="productId"><mat-option value="">Select product</mat-option>@for(product of data.products;track product.id){<mat-option [value]="product.id">{{product.name}} · {{money(product.price)}} · {{product.stockQuantity}} in stock</mat-option>}</mat-select></mat-form-field>
            <mat-form-field appearance="outline"><mat-label>Quantity</mat-label><input matInput type="number" min="1" formControlName="quantity"/></mat-form-field>
            <button mat-button type="button" [disabled]="items.length===1" (click)="removeItem(i)">Remove</button>
          </div>
        }
      </div>
    </mat-dialog-content>
    <mat-dialog-actions align="end"><button mat-button (click)="dialogRef.close()">Cancel</button><button mat-flat-button [disabled]="form.invalid||!hasItem()" (click)="submit()">Create order</button></mat-dialog-actions>
  `,
})
export class OrderFormDialogComponent {
  private readonly fb = inject(FormBuilder);
  readonly data = inject<OrderFormDialogData>(MAT_DIALOG_DATA);
  readonly dialogRef = inject(MatDialogRef<OrderFormDialogComponent, CreateOrderModel | undefined>);
  readonly money = formatCurrency;
  readonly form = this.fb.nonNullable.group({
    customerName: ['', Validators.required],
    customerPhone: [''],
    items: this.fb.array([this.createItem()]),
  });

  get items() { return this.form.controls.items; }
  addItem() { this.items.push(this.createItem()); }
  removeItem(index: number) { if (this.items.length > 1) this.items.removeAt(index); }
  hasItem() { return this.items.controls.some(item => Boolean(item.controls.productId.value) && item.controls.quantity.value > 0); }

  submit() {
    if (this.form.invalid || !this.hasItem()) { this.form.markAllAsTouched(); return; }
    const raw = this.form.getRawValue();
    this.dialogRef.close({
      customerName: raw.customerName.trim(),
      customerPhone: raw.customerPhone.trim() || null,
      items: raw.items.filter(item => item.productId).map(item => ({ productId: item.productId, quantity: Math.max(1, Number(item.quantity)) })),
    });
  }

  private createItem() {
    return this.fb.nonNullable.group({ productId: ['', Validators.required], quantity: [1, [Validators.required, Validators.min(1)]] });
  }
}
