// templates/clean-api/_variants/frontend/react/src/features/orders/pages/OrdersPage.tsx
import AddOutlinedIcon from '@mui/icons-material/AddOutlined';
import RefreshOutlinedIcon from '@mui/icons-material/RefreshOutlined';
import { Box, Button, MenuItem, Pagination, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import type { AuthUser } from '../../../core/auth/auth-session';
import { can } from '../../../core/auth/auth-session';
import { AsyncState } from '../../../shared/components/AsyncState';
import { ConfirmDialog } from '../../../shared/components/ConfirmDialog';
import { PageHeader } from '../../../shared/components/PageHeader';
import { useNotifications } from '../../../shared/feedback/NotificationProvider';
import { type BusinessListQuery, type ListFilter } from '../../../shared/query/business-query';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { ordersApi } from '../api/orders.api';
import { OrderFilters } from '../components/OrderFilters';
import { OrderFormDialog } from '../components/OrderFormDialog';
import { OrdersGrid } from '../components/OrdersGrid';
import type { CreateOrderModel, MutableOrderStatus, Order, OrderFilterState } from '../order.models';

type Props = { user: AuthUser };

const initialFilters: OrderFilterState = { keyword: '', sort: '', status: '', minTotal: '' };
const initialQuery: BusinessListQuery = { page: 1, pageSize: 20 };
const pageSizes = [10, 20, 50, 100];

export function OrdersPage({ user }: Props) {
  const queryClient = useQueryClient();
  const notifications = useNotifications();
  const [query, setQuery] = useState<BusinessListQuery>(initialQuery);
  const [filters, setFilters] = useState<OrderFilterState>(initialFilters);
  const [formOpen, setFormOpen] = useState(false);
  const [cancelTarget, setCancelTarget] = useState<Order | null>(null);

  const orders = useQuery({ queryKey: ['orders', query], queryFn: () => ordersApi.list(query) });
  const activeProducts = useQuery({
    queryKey: ['orders', 'active-products'],
    queryFn: ordersApi.activeProducts,
    enabled: formOpen,
    staleTime: 30_000,
  });

  const createOrder = useMutation({
    mutationFn: (model: CreateOrderModel) => ordersApi.create(model),
    onSuccess: async () => {
      notifications.success('Order created.');
      setFormOpen(false);
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ['orders'] }),
        queryClient.invalidateQueries({ queryKey: ['products'] }),
      ]);
    },
    onError: error => notifications.error(getErrorMessage(error)),
  });

  const updateStatus = useMutation({
    mutationFn: ({ order, status }: { order: Order; status: MutableOrderStatus }) => ordersApi.updateStatus(order.id, status),
    onSuccess: async (_, variables) => {
      notifications.success(`Order moved to ${variables.status}.`);
      await queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
    onError: error => notifications.error(getErrorMessage(error)),
  });

  const cancelOrder = useMutation({
    mutationFn: (order: Order) => ordersApi.cancel(order.id),
    onSuccess: async () => {
      notifications.success('Order cancelled.');
      setCancelTarget(null);
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ['orders'] }),
        queryClient.invalidateQueries({ queryKey: ['products'] }),
      ]);
    },
    onError: error => notifications.error(getErrorMessage(error)),
  });

  const applyFilters = () => {
    const lhs: ListFilter[] = [];
    if (filters.status) lhs.push({ field: 'Status', operator: '$eqi', value: filters.status });
    if (filters.minTotal.trim()) lhs.push({ field: 'TotalAmount', operator: '$gte', value: Math.max(0, Number(filters.minTotal)) });
    setQuery(current => ({
      ...current,
      page: 1,
      keyword: filters.keyword.trim() || undefined,
      targets: ['OrderNumber', 'CustomerName', 'CustomerPhone'],
      sort: filters.sort || undefined,
      filters: lhs,
    }));
  };

  const clearFilters = () => {
    setFilters(initialFilters);
    setQuery(current => ({ page: 1, pageSize: current.pageSize }));
  };

  const page = orders.data;
  const currentPage = page?.paging?.currentPage ?? query.page;
  const totalPages = page?.paging?.totalPage ?? 0;
  const busy = updateStatus.isPending || cancelOrder.isPending;

  return (
    <Box component="section">
      <PageHeader
        eyebrow="Sales"
        title="Orders"
        description="Create orders and move them through fulfillment."
        actions={(
          <>
            <Button variant="outlined" startIcon={<RefreshOutlinedIcon />} onClick={() => void orders.refetch()} disabled={orders.isFetching}>Refresh</Button>
            {can(user, 'orders.create') && <Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={() => setFormOpen(true)}>New order</Button>}
          </>
        )}
      />

      <OrderFilters value={filters} onChange={setFilters} onApply={applyFilters} onClear={clearFilters} />

      <AsyncState
        loading={orders.isLoading}
        error={orders.isError ? getErrorMessage(orders.error) : null}
        empty={!orders.isLoading && !orders.isError && (page?.data.length ?? 0) === 0}
        emptyTitle="No orders yet"
        emptyMessage="Create the first order or adjust the current filters."
        onRetry={() => void orders.refetch()}
      />

      {page && page.data.length > 0 && (
        <>
          <OrdersGrid
            orders={page.data}
            loading={orders.isFetching}
            busy={busy}
            canUpdate={can(user, 'orders.update-status')}
            canCancel={can(user, 'orders.cancel')}
            onUpdateStatus={(order, status) => updateStatus.mutate({ order, status })}
            onCancel={setCancelTarget}
          />
          {page.paging && (
            <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, alignItems: { sm: 'center' }, justifyContent: 'space-between', gap: 2, mt: 2 }}>
              <Typography variant="body2" color="text.secondary">{totalPages ? `Page ${currentPage} of ${totalPages}` : 'No results'}</Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                <TextField select size="small" label="Rows" value={query.pageSize} onChange={event => setQuery(current => ({ ...current, page: 1, pageSize: Number(event.target.value) }))} sx={{ width: 100 }}>
                  {pageSizes.map(size => <MenuItem key={size} value={size}>{size}</MenuItem>)}
                </TextField>
                <Pagination count={Math.max(1, totalPages)} page={Math.max(1, currentPage)} onChange={(_, nextPage) => setQuery(current => ({ ...current, page: nextPage }))} disabled={totalPages <= 1} />
              </Box>
            </Box>
          )}
        </>
      )}

      <OrderFormDialog
        open={formOpen}
        products={activeProducts.data?.data ?? []}
        productsLoading={activeProducts.isLoading || activeProducts.isFetching}
        productsError={activeProducts.isError ? getErrorMessage(activeProducts.error) : null}
        busy={createOrder.isPending}
        onClose={() => setFormOpen(false)}
        onSubmit={model => createOrder.mutate(model)}
      />
      <ConfirmDialog
        open={Boolean(cancelTarget)}
        title="Cancel order?"
        description={cancelTarget ? `Cancel ${cancelTarget.orderNumber}? Reserved stock will be restored.` : ''}
        confirmLabel="Cancel order"
        destructive
        busy={cancelOrder.isPending}
        onClose={() => setCancelTarget(null)}
        onConfirm={() => { if (cancelTarget) cancelOrder.mutate(cancelTarget); }}
      />
    </Box>
  );
}

// templates/clean-api/_variants/frontend/angular/src/app/features/orders/pages/orders.page.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { firstValueFrom } from 'rxjs';
import type { PaginationResponse } from '../../../core/api/api.models';
import { AuthSessionService } from '../../../core/auth/auth-session.service';
import { AsyncStateComponent } from '../../../shared/components/async-state.component';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';
import { PageHeaderComponent } from '../../../shared/components/page-header.component';
import { NotificationService } from '../../../shared/feedback/notification.service';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { FILTER_ENABLED, type BusinessListQuery, type ListFilter } from '../../business/business-query';
import { OrderFiltersComponent } from '../components/order-filters.component';
import { OrderFormDialogComponent } from '../components/order-form-dialog.component';
import { OrderTableComponent } from '../components/order-table.component';
import { OrdersApiService } from '../data-access/orders-api.service';
import type { CreateOrderModel, MutableOrderStatus, Order, OrderFilterState, ProductOption } from '../order.models';

@Component({
  selector: 'app-orders-page',
  standalone: true,
  imports: [MatButtonModule, MatFormFieldModule, MatSelectModule, PageHeaderComponent, AsyncStateComponent, OrderFiltersComponent, OrderTableComponent],
  styles: [`
    :host{display:block}.pager{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:16px;padding:12px 16px;border:1px solid var(--mat-sys-outline-variant);border-radius:16px;background:var(--mat-sys-surface)}.pager-actions{display:flex;align-items:center;gap:8px}.page-size{width:100px;margin-bottom:-20px}@media(max-width:599px){.pager{align-items:stretch;flex-direction:column}.pager-actions{justify-content:space-between}}
  `],
  template: `
    <app-page-header eyebrow="Sales" title="Orders" description="Create orders and move them through fulfillment.">
      <div pageActions><button mat-stroked-button (click)="load()" [disabled]="loading()">Refresh</button>@if(auth.can('orders.create')){<button mat-flat-button (click)="openForm()" [disabled]="loadingProducts()">{{loadingProducts()?'Loading…':'New order'}}</button>}</div>
    </app-page-header>

    @if(filterEnabled){<app-order-filters (applyFilters)="applyFilters($event)" (clearFilters)="clearFilters()"/>}

    <app-async-state [loading]="loading()" [error]="error()" [empty]="!loading()&&!error()&&(page()?.data?.length??0)===0" [showRetry]="true" emptyTitle="No orders yet" emptyMessage="Create the first order or adjust the current filters." (retry)="load()"/>

    @if(page(); as result){
      @if(result.data.length){
        <app-order-table [orders]="result.data" [busy]="actionBusy()" [canUpdate]="auth.can('orders.update-status')" [canCancel]="auth.can('orders.cancel')" (changeStatus)="updateStatus($event.order,$event.status)" (cancel)="cancelOrder($event)"/>
        @if(result.paging){<section class="pager"><span>{{result.paging.totalPage ? 'Page '+(result.paging.currentPage ?? query.page)+' of '+result.paging.totalPage : 'No results'}}</span><div class="pager-actions"><mat-form-field class="page-size" appearance="outline"><mat-label>Rows</mat-label><mat-select [value]="query.pageSize" (selectionChange)="changePageSize($event.value)">@for(size of pageSizes;track size){<mat-option [value]="size">{{size}}</mat-option>}</mat-select></mat-form-field><button mat-button [disabled]="!result.paging.hasPreviousPage" (click)="changePage(Math.max(1,(result.paging.currentPage ?? query.page)-1))">Prev</button><button mat-button [disabled]="!result.paging.hasNextPage" (click)="changePage((result.paging.currentPage ?? query.page)+1)">Next</button></div></section>}
      }
    }
  `,
})
export class OrdersPage implements OnInit {
  readonly auth = inject(AuthSessionService);
  readonly filterEnabled = FILTER_ENABLED;
  readonly pageSizes = [10, 20, 50, 100];
  readonly Math = Math;
  readonly loading = signal(false);
  readonly loadingProducts = signal(false);
  readonly actionBusy = signal(false);
  readonly error = signal<string | null>(null);
  readonly page = signal<PaginationResponse<Order> | null>(null);
  query: BusinessListQuery = { page: 1, pageSize: 20 };

  private readonly api = inject(OrdersApiService);
  private readonly dialog = inject(MatDialog);
  private readonly confirm = inject(ConfirmDialogService);
  private readonly notifications = inject(NotificationService);

  ngOnInit() { void this.load(); }

  async load() {
    this.loading.set(true); this.error.set(null);
    try { this.page.set(await firstValueFrom(this.api.list(this.query))); }
    catch (error) { this.error.set(getErrorMessage(error)); }
    finally { this.loading.set(false); }
  }

  applyFilters(filters: OrderFilterState) {
    const lhs: ListFilter[] = [];
    if (filters.status) lhs.push({ field: 'Status', operator: '$eqi', value: filters.status });
    if (filters.minTotal.trim()) lhs.push({ field: 'TotalAmount', operator: '$gte', value: Math.max(0, Number(filters.minTotal)) });
    this.query = { ...this.query, page: 1, keyword: filters.keyword.trim() || undefined, targets: ['OrderNumber', 'CustomerName', 'CustomerPhone'], sort: filters.sort || undefined, filters: lhs };
    void this.load();
  }

  clearFilters() { this.query = { page: 1, pageSize: this.query.pageSize }; void this.load(); }
  changePage(page: number) { this.query = { ...this.query, page }; void this.load(); }
  changePageSize(pageSize: number) { this.query = { ...this.query, page: 1, pageSize }; void this.load(); }

  async openForm() {
    this.loadingProducts.set(true);
    let products: ProductOption[];
    try { products = (await firstValueFrom(this.api.activeProducts())).data; }
    catch (error) { this.notifications.error(getErrorMessage(error)); return; }
    finally { this.loadingProducts.set(false); }

    const model = await firstValueFrom(this.dialog.open(OrderFormDialogComponent, { data: { products }, width: '780px', maxWidth: 'calc(100vw - 32px)', autoFocus: false }).afterClosed());
    if (model) await this.createOrder(model);
  }

  async createOrder(model: CreateOrderModel) {
    this.actionBusy.set(true);
    try { await firstValueFrom(this.api.create(model)); this.notifications.success('Order created.'); await this.load(); }
    catch (error) { this.notifications.error(getErrorMessage(error)); }
    finally { this.actionBusy.set(false); }
  }

  async updateStatus(order: Order, status: MutableOrderStatus) {
    this.actionBusy.set(true);
    try { await firstValueFrom(this.api.updateStatus(order.id, status)); this.notifications.success(`Order moved to ${status}.`); await this.load(); }
    catch (error) { this.notifications.error(getErrorMessage(error)); }
    finally { this.actionBusy.set(false); }
  }

  async cancelOrder(order: Order) {
    const confirmed = await this.confirm.confirm({ title: 'Cancel order?', description: `Cancel ${order.orderNumber}? Reserved stock will be restored.`, confirmLabel: 'Cancel order', destructive: true });
    if (!confirmed) return;
    this.actionBusy.set(true);
    try { await firstValueFrom(this.api.cancel(order.id)); this.notifications.success('Order cancelled.'); await this.load(); }
    catch (error) { this.notifications.error(getErrorMessage(error)); }
    finally { this.actionBusy.set(false); }
  }
}
