// templates/clean-api/_variants/frontend/react/src/features/todos/TodoPage.tsx
import { FormEvent, useState } from 'react';
import { buildPaginationItems } from '../../shared/pagination';
import { useCompleteTodo, useCreateTodo, useTodos } from './todo.queries';

type Props = { canWrite: boolean };

export function TodoPage({ canWrite }: Props) {
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [title, setTitle] = useState('');
  const todos = useTodos({ page, pageSize });
  const createTodo = useCreateTodo();
  const completeTodo = useCompleteTodo();
  const paging = todos.data?.paging;
  const currentPage = paging?.currentPage ?? page;
  const totalPages = Math.max(paging?.totalPage ?? 0, 1);
  const paginationItems = buildPaginationItems(currentPage, totalPages);

  function submit(event: FormEvent) {
    event.preventDefault();
    const value = title.trim();
    if (!value) return;
    createTodo.mutate(value, { onSuccess: () => { setTitle(''); setPage(1); } });
  }

  return <section className="card span-2">
    <div className="section-heading"><div><p className="eyebrow">Productivity</p><h2>Todo list</h2></div><button className="ghost" onClick={() => todos.refetch()}>Refresh</button></div>
    {canWrite && <form className="inline-form" onSubmit={submit}><input placeholder="What needs to be done?" value={title} onChange={event => setTitle(event.target.value)} /><button className="primary" disabled={createTodo.isPending}>Add task</button></form>}
    {todos.isLoading && <p className="muted">Loading tasks…</p>}
    {todos.error && <p className="error surface-error">Could not load todos.</p>}
    <ul className="todo-list">{todos.data?.data.map(todo => <li key={todo.id}><button className={`check ${todo.isCompleted ? 'checked' : ''}`} disabled={!canWrite || todo.isCompleted || completeTodo.isPending} onClick={() => completeTodo.mutate(todo.id)} aria-label="Complete todo">✓</button><div><strong className={todo.isCompleted ? 'done' : ''}>{todo.title}</strong><span>{new Date(todo.createdAtUtc).toLocaleString()}</span></div><span className={`pill ${todo.isCompleted ? 'success' : ''}`}>{todo.isCompleted ? 'Done' : 'Open'}</span></li>)}</ul>
    {!todos.isLoading && todos.data?.data.length === 0 && <div className="empty-state">No tasks on this page.</div>}
    <div className="pagination">
      <label>Rows<select value={pageSize} onChange={event => { setPageSize(Number(event.target.value)); setPage(1); }}><option>5</option><option>10</option><option>20</option></select></label>
      <div className="pagination-pages">
        <button disabled={!paging?.hasPreviousPage} onClick={() => setPage(value => Math.max(1, value - 1))}>Prev</button>
        {paginationItems.map((item, index) => item === 'ellipsis'
          ? <span className="pagination-ellipsis" key={`ellipsis-${index}`}>…</span>
          : <button key={item} className={`page-number ${item === currentPage ? 'active' : ''}`} aria-current={item === currentPage ? 'page' : undefined} onClick={() => setPage(item)}>{item}</button>)}
        <button disabled={!paging?.hasNextPage} onClick={() => setPage(value => value + 1)}>Next</button>
      </div>
    </div>
  </section>;
}

// templates/clean-api/_variants/frontend/angular/src/app/features/todos/todo.page.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { buildPaginationItems, PaginationItem } from '../../shared/pagination';
import { TodoStore } from './todo.store';

@Component({
  selector: 'app-todo-page',
  standalone: true,
  imports: [FormsModule],
  template: `<section class="card span-2">
    <div class="section-heading"><div><p class="eyebrow">Productivity</p><h2>Todo list</h2></div><button class="ghost" (click)="store.load()">Refresh</button></div>
    @if(auth.can('todos.write')){<form class="inline-form" (ngSubmit)="create()"><input name="title" [(ngModel)]="title" placeholder="What needs to be done?"/><button class="primary">Add task</button></form>}
    @if(store.loading()){<p class="muted">Loading tasks…</p>}
    @if(store.error()){<p class="error surface-error">{{store.error()}}</p>}
    <ul class="todo-list">@for(todo of store.items();track todo.id){<li><button class="check" [class.checked]="todo.isCompleted" [disabled]="!auth.can('todos.write')||todo.isCompleted" (click)="store.complete(todo.id)">✓</button><div><strong [class.done]="todo.isCompleted">{{todo.title}}</strong><span>{{todo.createdAtUtc}}</span></div><span class="pill" [class.success]="todo.isCompleted">{{todo.isCompleted?'Done':'Open'}}</span></li>}</ul>
    @if(!store.loading()&&store.items().length===0){<div class="empty-state">No tasks on this page.</div>}
    <div class="pagination">
      <label>Rows<select [ngModel]="store.pageSize()" (ngModelChange)="store.setPageSize(+$event)" [ngModelOptions]="{standalone:true}"><option [value]="5">5</option><option [value]="10">10</option><option [value]="20">20</option></select></label>
      <div class="pagination-pages">
        <button [disabled]="!store.hasPrevious()" (click)="store.setPage(store.page()-1)">Prev</button>
        @for(item of paginationItems();track $index){
          @if(item==='ellipsis'){<span class="pagination-ellipsis">…</span>}
          @else{<button class="page-number" [class.active]="item===store.page()" [attr.aria-current]="item===store.page()?'page':null" (click)="goToPage(item)">{{item}}</button>}
        }
        <button [disabled]="!store.hasNext()" (click)="store.setPage(store.page()+1)">Next</button>
      </div>
    </div>
  </section>`
})
export class TodoPage implements OnInit {
  readonly store = inject(TodoStore);
  readonly auth = inject(AuthSessionService);
  title = '';

  ngOnInit() { void this.store.load(); }

  paginationItems(): PaginationItem[] {
    return buildPaginationItems(this.store.page(), Math.max(this.store.totalPage(), 1));
  }

  goToPage(item: PaginationItem) {
    if (typeof item === 'number') void this.store.setPage(item);
  }

  async create() {
    const value = this.title.trim();
    if (!value) return;
    await this.store.create(value);
    this.title = '';
  }
}
