// templates/clean-api/_variants/frontend-app/angular-ai-storage/src/app/app.component.ts
import { Component,OnInit,inject,signal } from '@angular/core';
import { AuthSessionService,AuthUser } from './core/auth/auth-session.service';
import { LoginPage } from './features/auth/login.page';
import { BusinessWorkspaceComponent } from './features/business/business-workspace.component';
import { AiPage } from './features/ai/ai.page';
import { AppShellComponent } from './shared/components/app-shell.component';
@Component({selector:'app-root',standalone:true,imports:[LoginPage,BusinessWorkspaceComponent,AppShellComponent,AiPage],template:`@if(!ready()){<main class="shell"><p>Restoring session…</p></main>}@else if(!auth.user()){<app-login-page (authenticated)="onAuthenticated($event)"/>}@else{<app-shell [user]="auth.user()!" (logout)="onLogout()"><app-business-workspace/>@if(auth.can('ai.generate')){<app-ai-page/>}</app-shell>}`})
export class AppComponent implements OnInit{readonly auth=inject(AuthSessionService);readonly ready=signal(false);async ngOnInit(){await this.auth.bootstrap();this.ready.set(true);}onAuthenticated(_user:AuthUser){}async onLogout(){await this.auth.logout();}}

// templates/clean-api/_variants/frontend-app/react-ai-storage/src/app/App.tsx
import { useEffect, useState } from 'react';
import { bootstrapAuth, can, logout, type AuthUser } from '../core/auth/auth-session';
import { LoginPage } from '../features/auth/LoginPage';
import { AiPanel } from '../features/ai/AiPanel';
import { BusinessWorkspace } from '../features/business/BusinessWorkspace';
import { AppShell } from '../shared/components/AppShell';

export function App() {
  const [user, setUser] = useState<AuthUser | null | undefined>(undefined);
  useEffect(() => { void bootstrapAuth().then(setUser); }, []);
  if (user === undefined) return <main className="shell"><p>Restoring session…</p></main>;
  if (user === null) return <LoginPage onAuthenticated={setUser} />;
  return <AppShell user={user} onLogout={() => void logout().finally(() => setUser(null))}>
    <BusinessWorkspace
      user={user}
      onProfileUpdated={displayName => setUser(current => current ? { ...current, displayName } : current)}
      aiPanel={can(user, 'ai.generate') ? <AiPanel /> : undefined}
    />
  </AppShell>;
}
