// templates/clean-api/_variants/frontend-features/react-storage/src/features/storage/StorageBusinessWorkspace.tsx
import { useState, type ReactNode } from 'react';
import { can, type AuthUser } from '../../core/auth/auth-session';
import { BusinessWorkspace } from '../business/BusinessWorkspace';
import { ProductImagesWorkspace } from '../products/ProductImagesWorkspace';
import '../products/product-images.css';

type Props = {
  user: AuthUser;
  onProfileUpdated: (displayName: string) => void;
  aiPanel?: ReactNode;
};

export function StorageBusinessWorkspace({ user, onProfileUpdated, aiPanel }: Props) {
  const canViewProductImages = can(user, 'products.view');
  const [section, setSection] = useState<'operations' | 'images'>('operations');

  return <>
    {canViewProductImages && <div className="panel storage-workspace-tabs" role="tablist" aria-label="Workspace mode">
      <button type="button" className={section === 'operations' ? 'active' : ''} onClick={() => setSection('operations')}>Operations</button>
      <button type="button" className={section === 'images' ? 'active' : ''} onClick={() => setSection('images')}>Product Images</button>
    </div>}
    {section === 'images' && canViewProductImages
      ? <ProductImagesWorkspace user={user} />
      : <BusinessWorkspace user={user} onProfileUpdated={onProfileUpdated} aiPanel={aiPanel} />}
  </>;
}

// templates/clean-api/_variants/frontend-features/angular-storage/src/app/features/storage/storage-business-workspace.component.ts
import { Component, inject } from '@angular/core';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { BusinessWorkspaceComponent } from '../business/business-workspace.component';
import { ProductImagesWorkspaceComponent } from '../products/product-images-workspace.component';

@Component({
  selector:'app-storage-business-workspace',
  standalone:true,
  imports:[BusinessWorkspaceComponent,ProductImagesWorkspaceComponent],
  styles:[`.storage-workspace-tabs{display:flex;gap:8px;align-items:center;margin:0 0 18px;padding:7px;width:max-content;border:1px solid #e5e7eb;background:#fff;border-radius:16px}.storage-workspace-tabs button{border:0;background:transparent;border-radius:9px;padding:9px 14px;font-weight:750;color:#64748b;cursor:pointer}.storage-workspace-tabs button.active{background:#111827;color:#fff}@media(max-width:620px){.storage-workspace-tabs{width:100%}.storage-workspace-tabs button{flex:1}}`],
  template:`
    @if(auth.can('products.view')){<div class="storage-workspace-tabs" role="tablist" aria-label="Workspace mode"><button type="button" [class.active]="section==='operations'" (click)="section='operations'">Operations</button><button type="button" [class.active]="section==='images'" (click)="section='images'">Product Images</button></div>}
    @if(section==='images'&&auth.can('products.view')){<app-product-images-workspace/>}@else{<app-business-workspace/>}
  `
})
export class StorageBusinessWorkspaceComponent { readonly auth=inject(AuthSessionService);section:'operations'|'images'='operations'; }
