// templates/clean-api/_variants/frontend/react/src/features/settings/pages/SettingsPage.tsx
import SaveOutlinedIcon from '@mui/icons-material/SaveOutlined';
import { Box, Button, Paper, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { can, type AuthUser } from '../../../core/auth/auth-session';
import { AsyncState } from '../../../components/AsyncState';
import { PageHeader } from '../../../components/PageHeader';
import { useNotifications } from '../../../feedback/NotificationProvider';
import { getErrorMessage } from '../../../core/api/http-error';
import { configureCurrency } from '../../../utils/formatters';
import { settingsApi } from '../api/settings.api';
import type { StoreSettings } from '../settings.models';

export function SettingsPage({ user }: { user: AuthUser }) {
  const queryClient = useQueryClient();
  const notifications = useNotifications();
  const settings = useQuery({ queryKey: ['settings'], queryFn: settingsApi.get });
  const [draft, setDraft] = useState<StoreSettings | null>(null);
  const canUpdate = can(user, 'settings.update');

  useEffect(() => {
    if (!settings.data) return;
    setDraft(settings.data);
    configureCurrency(settings.data.currency);
  }, [settings.data]);

  const update = useMutation({
    mutationFn: settingsApi.update,
    onSuccess: async (_result, saved) => {
      configureCurrency(saved.currency);
      setDraft(saved);
      notifications.success('Settings saved.');
      await queryClient.invalidateQueries({ queryKey: ['settings'] });
    },
    onError: error => notifications.error(getErrorMessage(error)),
  });

  const set = <K extends keyof StoreSettings>(key: K, value: StoreSettings[K]) =>
    setDraft(current => current ? { ...current, [key]: value } : current);

  return (
    <Box component="section">
      <PageHeader
        eyebrow="System"
        title="Settings"
        description="Store identity and operational defaults. Currency controls every monetary value shown in the app."
        actions={canUpdate && draft ? (
          <Button variant="contained" startIcon={<SaveOutlinedIcon />} onClick={() => update.mutate(draft)} disabled={update.isPending}>
            {update.isPending ? 'Saving…' : 'Save settings'}
          </Button>
        ) : undefined}
      />
      <AsyncState loading={settings.isLoading} error={settings.isError ? getErrorMessage(settings.error) : null} onRetry={() => void settings.refetch()} />
      {draft && (
        <Paper variant="outlined" sx={{ p: { xs: 2, md: 3 }, borderRadius: 3 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 2 }}>Store defaults</Typography>
          <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2,minmax(0,1fr))' }, gap: 2 }}>
            <TextField label="Store name" value={draft.storeName} disabled={!canUpdate} onChange={e => set('storeName', e.target.value)} />
            <TextField label="Email" type="email" value={draft.storeEmail} disabled={!canUpdate} onChange={e => set('storeEmail', e.target.value)} />
            <TextField label="Phone" value={draft.storePhone} disabled={!canUpdate} onChange={e => set('storePhone', e.target.value)} />
            <TextField label="Currency" helperText="ISO 4217 code, for example VND, USD or EUR." value={draft.currency} disabled={!canUpdate} slotProps={{ htmlInput: { maxLength: 3 } }} onChange={e => set('currency', e.target.value.toUpperCase())} />
            <TextField label="Timezone" value={draft.timezone} disabled={!canUpdate} onChange={e => set('timezone', e.target.value)} />
            <TextField label="Low-stock threshold" type="number" value={draft.lowStockThreshold} disabled={!canUpdate} slotProps={{ htmlInput: { min: 0 } }} onChange={e => set('lowStockThreshold', Math.max(0, Number(e.target.value)))} />
          </Box>
          {!canUpdate && <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>You have read-only access to store settings.</Typography>}
        </Paper>
      )}
    </Box>
  );
}

// templates/clean-api/_variants/frontend/angular/src/app/features/settings/pages/settings.page.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { firstValueFrom } from 'rxjs';
import { AuthSessionService } from '../../../core/auth/auth-session.service';
import { AsyncStateComponent } from '../../../components/async-state.component';
import { PageHeaderComponent } from '../../../components/page-header.component';
import { NotificationService } from '../../../feedback/notification.service';
import { getErrorMessage } from '../../../core/api/http-error';
import { configureCurrency } from '../../../utils/formatters';
import { SettingsApiService } from '../data-access/settings-api.service';

@Component({ selector:'app-settings-page', standalone:true, imports:[ReactiveFormsModule,MatButtonModule,MatCardModule,MatFormFieldModule,MatInputModule,PageHeaderComponent,AsyncStateComponent], styles:[`:host{display:block}mat-card{border-radius:16px}mat-card-content{padding:24px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.full{grid-column:1/-1}@media(max-width:699px){.form-grid{grid-template-columns:1fr}}`], template:`<app-page-header eyebrow="System" title="Settings" description="Store identity and operational defaults. Currency controls every monetary value shown in the app."><div pageActions>@if(canUpdate){<button mat-flat-button (click)="save()" [disabled]="saving()||form.invalid">{{saving()?'Saving…':'Save settings'}}</button>}</div></app-page-header><app-async-state [loading]="loading()" [error]="error()" [showRetry]="true" (retry)="load()"/>@if(!loading()&&!error()){<mat-card appearance="outlined"><mat-card-content><form [formGroup]="form" class="form-grid"><mat-form-field appearance="outline"><mat-label>Store name</mat-label><input matInput formControlName="storeName"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="storeEmail"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Phone</mat-label><input matInput formControlName="storePhone"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Currency</mat-label><input matInput maxlength="3" formControlName="currency" (input)="uppercaseCurrency()"/><mat-hint>ISO 4217 code, for example VND, USD or EUR.</mat-hint></mat-form-field><mat-form-field appearance="outline"><mat-label>Timezone</mat-label><input matInput formControlName="timezone"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Low-stock threshold</mat-label><input matInput type="number" min="0" formControlName="lowStockThreshold"/></mat-form-field></form></mat-card-content></mat-card>}` })
export class SettingsPage implements OnInit {
  readonly auth=inject(AuthSessionService);
  readonly canUpdate=this.auth.can('settings.update');
  readonly loading=signal(false);
  readonly saving=signal(false);
  readonly error=signal<string|null>(null);
  private readonly api=inject(SettingsApiService);
  private readonly notifications=inject(NotificationService);
  private readonly fb=inject(FormBuilder);
  readonly form=this.fb.nonNullable.group({storeName:['',Validators.required],storeEmail:['',[Validators.required,Validators.email]],storePhone:[''],currency:['VND',[Validators.required,Validators.minLength(3),Validators.maxLength(3)]],timezone:['UTC',Validators.required],lowStockThreshold:[0,[Validators.required,Validators.min(0)]]});

  ngOnInit(){if(!this.canUpdate)this.form.disable();void this.load();}

  async load(){
    this.loading.set(true);
    this.error.set(null);
    try{
      const value=await firstValueFrom(this.api.get());
      this.form.patchValue(value);
      configureCurrency(value.currency);
    }catch(error){this.error.set(getErrorMessage(error));}
    finally{this.loading.set(false);}
  }

  uppercaseCurrency(){const control=this.form.controls.currency;const next=control.value.toUpperCase();if(next!==control.value)control.setValue(next,{emitEvent:false});}

  async save(){
    if(!this.canUpdate||this.form.invalid)return;
    const model=this.form.getRawValue();
    this.saving.set(true);
    try{
      await firstValueFrom(this.api.update(model));
      configureCurrency(model.currency);
      this.notifications.success('Settings saved.');
      await this.load();
    }catch(error){this.notifications.error(getErrorMessage(error));}
    finally{this.saving.set(false);}
  }
}
